### PR TITLE
Add owner/repo get_repo endpoint function

### PR DESCRIPTION
**Pull request by fchorney**
Looks like this was missed in https://github.com/JuliaWeb/GitForge.jl/pull/26
Seems like you need to also add the function signature here

@mattBrzezinski

### CODE REVIEW

**Review by mattBrzezinski — APPROVED** [review]
Oh that makes sense!

LGTM just needs a version bump. Probably should have CDG double check if there is anything else needed here. Also, would be nice to incorporate some testing here as well, although that's a bit tricky.

**Comment by fchorney** [comment]
> Oh that makes sense!
> 
> LGTM just needs a version bump. Probably should have CDG double check if there is anything else needed here. Also, would be nice to incorporate some testing here as well, although that's a bit tricky.

good call, I'm terrible for forgetting about the version bump. @christopher-dG if you have a chance could you confirm this is the only fix we need for this?

**Comment by mattBrzezinski** [comment]
> > Oh that makes sense!
> > LGTM just needs a version bump. Probably should have CDG double check if there is anything else needed here. Also, would be nice to incorporate some testing here as well, although that's a bit tricky.
> 
> good call, I'm terrible for forgetting about the version bump. @christopher-dG if you have a chance could you confirm this is the only fix we need for this?

I have an odd system to the version bump stuff. In most cases I will exclude the bump in the PR, unless in a situation like this where there is a very small change and the PR should reasonably go through almost instantly. Otherwise I create a PR for a version bump separately, especially in the case where multiple things will go into the new version.

**Review by christopher-dG — APPROVED** [review]
LGTM, sorry I missed this the first time around.

**Pull request merged**
